config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :products

  root to: 'products#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
require 'csv'

def self.to_csv(options = {})
  desired_columns = ["id", "name", "released_on", "price"]
  CSV.generate(options) do |csv|
    csv << desired_columns
    all.each do |product|
      csv << product.attributes.values_at(*desired_columns)
    end
  end
end




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
def index
  @products = Product.order(:name)

 
respond_to do |format|
  format.html
  format.csv {
  	send_data @products.to_csv
}

csv_data = @products.to_csv
MymailerMailer.send_csv(csv_data).deliver


end

end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CsvHelper</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div id="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, id: "flash_#{name}" %>
    <% end %>
    <%= yield %>
  </div>
</body>

</html>

app/views/products/_product.html.erb
<tr>
  <td><%= product.name %></td>
  <td><%= product.released_on.strftime("%B %e, %Y") %></td>
  <td><%= number_to_currency(product.price) %></td>
</tr>

app/views/products/index.html.erb
<h1>Products</h1>
<table id="products">
  <tr>
    <th>Product Name</th>
    <th>Release Date</th>
    <th>Price</th>
  </tr>
<%= render @products %>
</table>
<p>
  Download:
  <%= link_to "CSV", products_path(format: "csv") %> |
  <%= link_to "Excel", products_path(format: "xls") %>
</p>